version: 2
jobs:
  verify:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - model-{{ checksum "package-lock.json" }}
            - model-
      - run: npm install
      - save_cache:
          paths:
            - model/node_modules
          key: model-{{ checksum "package-lock.json" }}
      - run: npm run ci
workflows:
  version: 2
  main-workflow:
    jobs:
      - verify
